name: CI/CD for Minikube

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Code from GitHub
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set Up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Log in to Docker Hub (Use GitHub Secrets)
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 4: Build and Push Docker Image
    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/gwa1:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/gwa1:latest

    # Step 5: Set Up Minikube
    - name: Set up Minikube
      uses: medyagh/setup-minikube@latest

    # Step 6: Configure kubectl to use Minikube
    - name: Configure kubectl
      run: |
        kubectl config use-context minikube

    # Step 7: Deploy Application to Minikube
    - name: Apply Kubernetes Manifests
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml

    # Step 8: Get Minikube Service URL
    - name: Get Minikube Service URL
      run: |
        echo "Website URL: $(minikube service gwa1 --url)" >> $GITHUB_STEP_SUMMARY
